/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.pages.CommitteeAccountPage;

import main.java.ApplicationContext;
import main.java.models.User;
import main.java.pages.BasePage;
import main.java.services.UserService;

import java.io.FileNotFoundException;

/**
 *
 * @author Zhi Yan
 */
public class CommitteeAccountPage extends BasePage {

    /**
     * Creates new form CPage3
     */
    public CommitteeAccountPage(ApplicationContext applicationContext) throws FileNotFoundException {
        super(applicationContext);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        Modify1 = new javax.swing.JButton();
        Modify2 = new javax.swing.JButton();
        Modify4 = new javax.swing.JButton();
        Modify5 = new javax.swing.JButton();
        jPanel_main = new javax.swing.JPanel();
        jPanel_personal_info = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area_main = new javax.swing.JTextArea();
        btn_people_account = new javax.swing.JButton();
        btn_get_personal_info = new javax.swing.JButton();
        VacAppoint = new javax.swing.JButton();
        Supply = new javax.swing.JButton();
        StatRe = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Modify = new javax.swing.JButton();

        Modify1.setBackground(new java.awt.Color(102, 102, 102));
        Modify1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Modify1.setForeground(new java.awt.Color(255, 255, 255));
        Modify1.setText("Modify");
        Modify1.setToolTipText("");

        Modify2.setBackground(new java.awt.Color(102, 102, 102));
        Modify2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Modify2.setForeground(new java.awt.Color(255, 255, 255));
        Modify2.setText("Modify");
        Modify2.setToolTipText("");

        Modify4.setBackground(new java.awt.Color(102, 102, 102));
        Modify4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Modify4.setForeground(new java.awt.Color(255, 255, 255));
        Modify4.setText("Modify");
        Modify4.setToolTipText("");

        Modify5.setBackground(new java.awt.Color(102, 102, 102));
        Modify5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Modify5.setForeground(new java.awt.Color(255, 255, 255));
        Modify5.setText("Modify");
        Modify5.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_main.setBackground(new java.awt.Color(0, 102, 102));

        jPanel_personal_info.setBackground(new java.awt.Color(204, 204, 204));

        text_area_main.setColumns(20);
        text_area_main.setRows(5);
        jScrollPane1.setViewportView(text_area_main);

        javax.swing.GroupLayout jPanel_personal_infoLayout = new javax.swing.GroupLayout(jPanel_personal_info);
        jPanel_personal_info.setLayout(jPanel_personal_infoLayout);
        jPanel_personal_infoLayout.setHorizontalGroup(
            jPanel_personal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_personal_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel_personal_infoLayout.setVerticalGroup(
            jPanel_personal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_personal_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_people_account.setBackground(new java.awt.Color(102, 102, 102));
        btn_people_account.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_people_account.setForeground(new java.awt.Color(255, 255, 255));
        btn_people_account.setText("People Account");
        btn_people_account.setToolTipText("");
        btn_people_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeToPeopleAccountPage(evt);
            }
        });

        btn_get_personal_info.setBackground(new java.awt.Color(102, 102, 102));
        btn_get_personal_info.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_get_personal_info.setForeground(new java.awt.Color(255, 255, 255));
        btn_get_personal_info.setText("Personal Info");
        btn_get_personal_info.setToolTipText("");
        btn_get_personal_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    get_personal_info(evt);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });

        VacAppoint.setBackground(new java.awt.Color(102, 102, 102));
        VacAppoint.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        VacAppoint.setForeground(new java.awt.Color(255, 255, 255));
        VacAppoint.setText("Vaccination Appointments");
        VacAppoint.setToolTipText("");
        VacAppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VacAppointActionPerformed(evt);
            }
        });

        Supply.setBackground(new java.awt.Color(102, 102, 102));
        Supply.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Supply.setForeground(new java.awt.Color(255, 255, 255));
        Supply.setText("Supply of Vaccines");
        Supply.setToolTipText("");
        Supply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplyActionPerformed(evt);
            }
        });

        StatRe.setBackground(new java.awt.Color(102, 102, 102));
        StatRe.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        StatRe.setForeground(new java.awt.Color(255, 255, 255));
        StatRe.setText("Statistical Reports");
        StatRe.setToolTipText("");
        StatRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatReActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.setToolTipText("");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("WELCOME TO");
        jLabel4.setToolTipText("");
        jLabel4.setName("header_1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COVID-19 VACCINE REGISTRATION SYSTEM");
        jLabel1.setToolTipText("");

        Delete.setBackground(new java.awt.Color(102, 102, 102));
        Delete.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.setToolTipText("");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDelete(evt);
            }
        });

        Save.setBackground(new java.awt.Color(102, 102, 102));
        Save.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.setToolTipText("");

        Modify.setBackground(new java.awt.Color(102, 102, 102));
        Modify.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Modify.setForeground(new java.awt.Color(255, 255, 255));
        Modify.setText("Modify");
        Modify.setToolTipText("");
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onModity(evt);
            }
        });

        javax.swing.GroupLayout jPanel_mainLayout = new javax.swing.GroupLayout(jPanel_main);
        jPanel_main.setLayout(jPanel_mainLayout);
        jPanel_mainLayout.setHorizontalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_get_personal_info, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_people_account, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supply, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StatRe, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VacAppoint)
                            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_personal_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1337, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel_mainLayout.setVerticalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addComponent(btn_get_personal_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_people_account, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(VacAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Supply, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StatRe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_personal_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Modify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void routeToPeopleAccountPage(java.awt.event.ActionEvent evt) {                                      
        this.applicationContext.getCommitteeAccountPage().setVisible(false);
        this.applicationContext.getLoginPage().setVisible(true);
    }

    private void get_personal_info(java.awt.event.ActionEvent evt) throws FileNotFoundException {//GEN-FIRST:event_get_personal_info
        this.applicationContext.setCurrentMode("personal_info");
        final String newLine = "\n";
        String contents = "";
        UserService userService = new UserService();
        User userDetails = userService.viewUser(this.applicationContext.getCurrentUsername());
        text_area_main.setText("");
        contents += "Username: " + userDetails.getUsername();
        contents += newLine;
        contents += "Password: " + userDetails.getPassword();
        contents += newLine;
        contents += "Actual Name: " + userDetails.getActualName();
        contents += newLine;
        contents += "Nationality: " + userDetails.getNationality();
        contents += newLine;
        contents += "Date of Birth: " + userDetails.getDateOfBirth();
        contents += newLine;
        contents += "Gender: " + userDetails.getGender();
        contents += newLine;
        contents += "Contact No: " + userDetails.getContactNo();
        contents += newLine;
        contents += "Email: " + userDetails.getEmail();
        contents += newLine;
        contents += "Address: " + userDetails.getAddress();
        contents += newLine;
        contents += "Postcode: " + userDetails.getPostcode();
        contents += newLine;
        contents += "City: " + userDetails.getCity();
        contents += newLine;
        contents += "State: " + userDetails.getState();
        contents += newLine;
        contents += "Role: " + userDetails.getRole();
        text_area_main.setText(contents);
        text_area_main.setEditable(false);

//        for (String row: text_area_main.getText().split("\n")){
//            System.out.println("row: " + row);
//        }
    }//GEN-LAST:event_get_personal_info

    private void VacAppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VacAppointActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        CPage6_VacAppointment VacAppoint= new CPage6_VacAppointment();
//        VacAppoint.setVisible(true);
    }//GEN-LAST:event_VacAppointActionPerformed

    private void SupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplyActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        CPage7_SupplyVac Supply= new CPage7_SupplyVac();
//        Supply.setVisible(true);
    }//GEN-LAST:event_SupplyActionPerformed

    private void StatReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatReActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        CPage8_Report StatRe= new CPage8_Report();
//        StatRe.setVisible(true);
    }//GEN-LAST:event_StatReActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        Page2_Committee compage1= new Page2_Committee();
//        compage1.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void onModity(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onModity
        // TODO add your handling code here:

        if (this.applicationContext.getCurrentMode().equals("personal_info")) {
            // Modify Personal Info Module
            text_area_main.setEditable(true);
        } else if (this.applicationContext.getCurrentMode().equals("xxx")) {
            /// Modify xxx

        }

    }//GEN-LAST:event_onModity

    private void onDelete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDelete
        // TODO add your handling code here:
        if (this.applicationContext.getCurrentMode().equals("personal_info")) {
            // Delete Personal Info Module
            \iuuyjmjtnhhrrgrb
        } else if (this.applicationContext.getCurrentMode().equals("xxx")) {
            /// Modify xxx

        }
    }//GEN-LAST:event_onDelete

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Modify;
    private javax.swing.JButton Modify1;
    private javax.swing.JButton Modify2;
    private javax.swing.JButton Modify4;
    private javax.swing.JButton Modify5;
    private javax.swing.JButton Save;
    private javax.swing.JButton StatRe;
    private javax.swing.JButton Supply;
    private javax.swing.JButton VacAppoint;
    private javax.swing.JButton btn_get_personal_info;
    private javax.swing.JButton btn_people_account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_personal_info;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextArea text_area_main;
    // End of variables declaration//GEN-END:variables
}
