/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.pages.PeopleAccountPage;

import assignment.*;
import main.java.ApplicationContext;
import main.java.models.User;
import main.java.pages.BasePage;
import main.java.services.UserService;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Zhi Yan
 */
public class PeopleAccountPage extends BasePage {

    UserService userService;
    List<User> peopleList;

    public PeopleAccountPage(ApplicationContext applicationContext) throws FileNotFoundException {
        super(applicationContext);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        jPanel_main = new javax.swing.JPanel();
        jPanel_personal_info = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area_main = new javax.swing.JTextArea();
        btn_get_personal_info = new javax.swing.JButton();
        RegVac = new javax.swing.JButton();
        VacStatus = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_main.setBackground(new java.awt.Color(0, 102, 102));

        jPanel_personal_info.setBackground(new java.awt.Color(204, 204, 204));

        text_area_main.setColumns(20);
        text_area_main.setRows(5);
        jScrollPane1.setViewportView(text_area_main);

        javax.swing.GroupLayout jPanel_personal_infoLayout = new javax.swing.GroupLayout(jPanel_personal_info);
        jPanel_personal_info.setLayout(jPanel_personal_infoLayout);
        jPanel_personal_infoLayout.setHorizontalGroup(
            jPanel_personal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_personal_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel_personal_infoLayout.setVerticalGroup(
            jPanel_personal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_personal_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_get_personal_info.setBackground(new java.awt.Color(102, 102, 102));
        btn_get_personal_info.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_get_personal_info.setForeground(new java.awt.Color(255, 255, 255));
        btn_get_personal_info.setText("Personal Info");
        btn_get_personal_info.setToolTipText("");
        btn_get_personal_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn_get_personal_infoget_personal_info(evt);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });

        RegVac.setBackground(new java.awt.Color(102, 102, 102));
        RegVac.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        RegVac.setForeground(new java.awt.Color(255, 255, 255));
        RegVac.setText("Register Vaccination");
        RegVac.setToolTipText("");
        RegVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegVacActionPerformed(evt);
            }
        });

        VacStatus.setBackground(new java.awt.Color(102, 102, 102));
        VacStatus.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        VacStatus.setForeground(new java.awt.Color(255, 255, 255));
        VacStatus.setText("Vaccination Status");
        VacStatus.setToolTipText("");
        VacStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VacStatusActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.setToolTipText("");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("WELCOME TO");
        jLabel7.setToolTipText("");
        jLabel7.setName("header_1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COVID-19 VACCINE REGISTRATION SYSTEM");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel_mainLayout = new javax.swing.GroupLayout(jPanel_main);
        jPanel_main.setLayout(jPanel_mainLayout);
        jPanel_mainLayout.setHorizontalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1363, Short.MAX_VALUE)))
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_mainLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_mainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VacStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegVac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_get_personal_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addComponent(jPanel_personal_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_mainLayout.setVerticalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addComponent(btn_get_personal_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegVac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(VacStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_personal_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_get_personal_infoget_personal_info(java.awt.event.ActionEvent evt) throws FileNotFoundException {//GEN-FIRST:event_btn_get_personal_infoget_personal_info
        final String newLine = "\n";
        String contents = "";
        UserService userService = new UserService();
        User userDetails = userService.viewUser(this.applicationContext.getCurrentUsername());
        text_area_main.setText("");
        contents += "Username: " + userDetails.getUsername();
        contents += newLine;
        contents += "Password: " + userDetails.getPassword();
        contents += newLine;
        contents += "Actual Name: " + userDetails.getActualName();
        contents += newLine;
        contents += "Nationality: " + userDetails.getNationality();
        contents += newLine;
        contents += "Date of Birth: " + userDetails.getDateOfBirth();
        contents += newLine;
        contents += "Gender: " + userDetails.getGender();
        contents += newLine;
        contents += "Contact No: " + userDetails.getContactNo();
        contents += newLine;
        contents += "Email: " + userDetails.getEmail();
        contents += newLine;
        contents += "Address: " + userDetails.getAddress();
        contents += newLine;
        contents += "Postcode: " + userDetails.getPostcode();
        contents += newLine;
        contents += "City: " + userDetails.getCity();
        contents += newLine;
        contents += "State: " + userDetails.getState();
        contents += newLine;
        contents += "Role: " + userDetails.getRole();
        text_area_main.setText(contents);

        //        for (String row: text_area_main.getText().split("\n")){
            //            System.out.println("row: " + row);
            //        }
    }//GEN-LAST:event_btn_get_personal_infoget_personal_info

    private void RegVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegVacActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //        CPage6_VacAppointment VacAppoint= new CPage6_VacAppointment();
        //        VacAppoint.setVisible(true);
    }//GEN-LAST:event_RegVacActionPerformed

    private void VacStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VacStatusActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //        CPage7_SupplyVac Supply= new CPage7_SupplyVac();
        //        Supply.setVisible(true);
    }//GEN-LAST:event_VacStatusActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //        Page2_Committee compage1= new Page2_Committee();
        //        compage1.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegVac;
    private javax.swing.JButton VacStatus;
    private javax.swing.JButton btn_get_personal_info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_personal_info;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextArea text_area_main;
    // End of variables declaration//GEN-END:variables
}
