
package assignment;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class CPage1 extends javax.swing.JFrame {

    public CPage1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jPanel_container = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        CReturn = new javax.swing.JButton();
        CUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CSeenPw1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        CRealName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CDOB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CContactNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CPostcode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CCity = new javax.swing.JTextField();
        CRegister = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Lab1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CPassword1 = new javax.swing.JPasswordField();
        CNoIC = new javax.swing.JTextField();
        PGender = new javax.swing.JLabel();
        CFemale = new javax.swing.JRadioButton();
        CMale = new javax.swing.JRadioButton();
        CPassword2 = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        CSeenPw2 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        CAddress = new javax.swing.JTextArea();
        CState = new javax.swing.JTextField();
        CNationality = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(java.awt.Color.white);

        jPanel_container.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(218, 218, 218));

        Title.setBackground(new java.awt.Color(204, 204, 204));
        Title.setFont(new java.awt.Font("Segoe UI Black", 1, 25)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Register");
        Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        CReturn.setBackground(new java.awt.Color(255, 0, 51));
        CReturn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CReturn.setForeground(new java.awt.Color(255, 255, 255));
        CReturn.setText("Return");
        CReturn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CReturnMouseClicked(evt);
            }
        });
        CReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CReturnActionPerformed(evt);
            }
        });

        CUsername.setToolTipText("Example123");
        CUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUsernameActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Username");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password");

        CSeenPw1.setForeground(new java.awt.Color(102, 102, 102));
        CSeenPw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSeenPw1ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Full Name");

        CRealName.setToolTipText("Chye Zee Ching");
        CRealName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRealNameActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("IC / Passport No");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Date Of Birth");

        CDOB.setToolTipText("YYYDDMM \"20001122\"");
        CDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDOBActionPerformed(evt);
            }
        });
        CDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CDOBKeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Contact No");

        CContactNo.setToolTipText("0123456789");
        CContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CContactNoActionPerformed(evt);
            }
        });
        CContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CContactNoKeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Email");

        CEmail.setToolTipText("Examnple123@email.com");
        CEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEmailActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Address");

        CPostcode.setToolTipText("54000");
        CPostcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPostcodeActionPerformed(evt);
            }
        });
        CPostcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPostcodeKeyTyped(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Postcode");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("City");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("State");

        CCity.setToolTipText("Bukit Jalil");
        CCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCityActionPerformed(evt);
            }
        });

        CRegister.setBackground(new java.awt.Color(0, 153, 153));
        CRegister.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CRegister.setForeground(new java.awt.Color(0, 0, 0));
        CRegister.setText("Register");
        CRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRegisterActionPerformed(evt);
            }
        });

        CPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPassword1ActionPerformed(evt);
            }
        });

        CNoIC.setToolTipText("001122101234");
        CNoIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CNoICKeyTyped(evt);
            }
        });

        PGender.setForeground(new java.awt.Color(0, 0, 0));
        PGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PGender.setText("Gender");

        CFemale.setText("Female");
        CFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFemaleActionPerformed(evt);
            }
        });

        CMale.setText("Male");
        CMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMaleActionPerformed(evt);
            }
        });

        CPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPassword2ActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Confirm Password");

        CSeenPw2.setForeground(new java.awt.Color(102, 102, 102));
        CSeenPw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSeenPw2ActionPerformed(evt);
            }
        });

        CAddress.setColumns(20);
        CAddress.setRows(5);
        jScrollPane1.setViewportView(CAddress);

        CState.setToolTipText("Bukit Jalil");
        CState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CStateActionPerformed(evt);
            }
        });

        CNationality.setToolTipText("Malaysian");
        CNationality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CNationalityKeyTyped(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Nationality");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CUsername)
                                    .addComponent(CPassword1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSeenPw1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSeenPw2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CNationality)
                            .addComponent(CNoIC)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CRealName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CDOB)
                            .addComponent(CContactNo)
                            .addComponent(CEmail)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(CPostcode)
                            .addComponent(CCity)
                            .addComponent(CState))
                        .addGap(25, 25, 25)))
                .addComponent(Lab1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addGap(7, 7, 7)
                .addComponent(jLabel16)
                .addGap(90, 90, 90))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CRegister)
                .addGap(127, 127, 127)
                .addComponent(CReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(Lab1)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CSeenPw1)
                    .addComponent(CPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CSeenPw2)
                    .addComponent(jLabel17))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CRealName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNoIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PGender)
                    .addComponent(CMale)
                    .addComponent(CFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CRegister)
                    .addComponent(CReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_containerLayout = new javax.swing.GroupLayout(jPanel_container);
        jPanel_container.setLayout(jPanel_containerLayout);
        jPanel_containerLayout.setHorizontalGroup(
            jPanel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_containerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel_containerLayout.setVerticalGroup(
            jPanel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_containerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CReturnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Page1 startPage= new Page1();
        startPage.setVisible(true);
    }//GEN-LAST:event_CReturnMouseClicked

    private void CReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CReturnActionPerformed
        this.dispose();
        Page3 committeePage= new Page3();
        committeePage.setVisible(true);
    }//GEN-LAST:event_CReturnActionPerformed

    private void CUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CUsernameActionPerformed

    private void CSeenPw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSeenPw1ActionPerformed
        // Show and hide password:
        if(CSeenPw1.isSelected()){
            CPassword1.setEchoChar((char)0);
        }else{
            CPassword1.setEchoChar((char)'*');
        }
        //sas
    }//GEN-LAST:event_CSeenPw1ActionPerformed

    private void CRealNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRealNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CRealNameActionPerformed

    private void CDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDOBActionPerformed

    private void CDOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CDOBKeyTyped
        // TODO numeric only:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_CDOBKeyTyped

    private void CContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CContactNoActionPerformed

    private void CContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CContactNoKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_CContactNoKeyTyped

    private void CEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEmailActionPerformed

    private void CPostcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPostcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPostcodeActionPerformed

    private void CPostcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPostcodeKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_CPostcodeKeyTyped

    private void CCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCityActionPerformed

    private void CRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRegisterActionPerformed
        String username = CUsername.getText();
        String pw1 = String.valueOf(CPassword1.getPassword());
        String pw2 = String.valueOf(CPassword2.getPassword());
        String name = CRealName.getText();
        String ic = CNoIC.getText();
        String nationality = CNationality.getText();
        String dob = CDOB.getText();
        String contact = CContactNo.getText();
        String email = CEmail.getText();
        String address = CAddress.getText();
        String postcode = CPostcode.getText();
        String city = CCity.getText();
        String state = CState.getText();
        
        String gender = null;
        if(CMale.isSelected()){
            gender = "Male";
        }else if(CFemale.isSelected()){
            gender = "Female";
        }
        
        try{
            File comfile = new File("Committee.txt");
            boolean x = false;
            while(x == false){
                if(username.isBlank() || pw1.isBlank() || pw2.isBlank() || name.isBlank() || ic.isBlank() || dob.isBlank() ||
                    contact.isBlank() || email.isBlank() || address.isBlank() || postcode.isBlank() ||
                    city.isBlank() || state.isBlank()){
                    JOptionPane.showMessageDialog(CCity, "Please fill out the blank space!");
                    x=false;
                    break;
                }else if(!(pw1.equals(pw2))){
                    
                    JOptionPane.showMessageDialog(CPassword2, "Please ensure both entered password matches!");
                    x=false;
                    break;
                }else if(pw1.equals(pw2)){
                    String data = CUsername.getText();
                    try {
                        Scanner sc = new Scanner(comfile); // file object
                        while (sc.hasNextLine()) {
                            data = sc.nextLine(); // file content
                            data = data.split(":")[1];
                            data = data.replaceAll("\\s+", "");
                            if (data.equals(username.trim())){
                                JOptionPane.showMessageDialog(CPassword2, "Username is taken! Please try again.");
                                break;
                            }else{
                                x=true;
                                BufferedWriter cfile = new BufferedWriter(new FileWriter(comfile, true)); 
                                cfile.write("Username: "+username+"\nPassword: "+pw1+"\nFull Name: "+name+"\nIC / Passport No: "+ic+ "\nNationalty: "+nationality+
                                    "\nGender: "+gender+ "\nDate of Birth: "+dob+"\nContact No: "+contact+"\nEmail: "+email+"\nAddress: "+address+
                                    "\nPostcode: "+postcode+"\nCity: "+city+"\nState: "+state+"\n\n");
                                cfile.close();
                                JOptionPane.showMessageDialog(CCity, "Dear "+name+",\n\nYou have registered successfully! You may proceed to login.");
                                setVisible(true);
                                this.dispose();
                                Page2 CommitteePage= new Page2();
                                CommitteePage.setVisible(true);
                                break;
                            }
                        }
                        sc.close();
                        x=false;
                        break;
                    } catch (FileNotFoundException ex) {
                        System.out.println("ERROR: "+ex);
                    }
                }else{
                    
                }

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(CCity,"Error! Please try again.");
        }
    }//GEN-LAST:event_CRegisterActionPerformed

    private void CPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPassword1ActionPerformed

    private void CNoICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CNoICKeyTyped
        // TODO numeric only:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_CNoICKeyTyped

    private void CFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFemaleActionPerformed
        // TODO add your handling code here:
        if(CFemale.isSelected()){
            CMale.setSelected(false);
        }
    }//GEN-LAST:event_CFemaleActionPerformed

    private void CPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPassword2ActionPerformed

    private void CSeenPw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSeenPw2ActionPerformed
        // TODO add your handling code here:
        if(CSeenPw2.isSelected()){
            CPassword2.setEchoChar((char)0);
        }else{
            CPassword2.setEchoChar((char)'*');
        }
    }//GEN-LAST:event_CSeenPw2ActionPerformed

    private void CStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CStateActionPerformed

    private void CNationalityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CNationalityKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CNationalityKeyTyped

    private void CMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMaleActionPerformed
        // TODO add your handling code here:
        if(CMale.isSelected()){
            CFemale.setSelected(false);
        }
    }//GEN-LAST:event_CMaleActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CAddress;
    private javax.swing.JTextField CCity;
    private javax.swing.JTextField CContactNo;
    private javax.swing.JTextField CDOB;
    private javax.swing.JTextField CEmail;
    private javax.swing.JRadioButton CFemale;
    private javax.swing.JRadioButton CMale;
    private javax.swing.JTextField CNationality;
    private javax.swing.JTextField CNoIC;
    private javax.swing.JPasswordField CPassword1;
    private javax.swing.JPasswordField CPassword2;
    private javax.swing.JTextField CPostcode;
    private javax.swing.JTextField CRealName;
    private javax.swing.JButton CRegister;
    private javax.swing.JButton CReturn;
    private javax.swing.JCheckBox CSeenPw1;
    private javax.swing.JCheckBox CSeenPw2;
    private javax.swing.JTextField CState;
    private javax.swing.JTextField CUsername;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel PGender;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_container;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
