/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ching
 */
public class PPage2_Login extends javax.swing.JFrame {

    /**
     * Creates new form PPage2
     */
    public PPage2_Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_title1 = new javax.swing.JLabel();
        PReturn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PUsername = new javax.swing.JTextField();
        PSignIn = new javax.swing.JButton();
        PForgot = new javax.swing.JButton();
        PPassword = new javax.swing.JPasswordField();
        PSeenPw = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel_title1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_title1.setFont(new java.awt.Font("Segoe UI Black", 1, 25)); // NOI18N
        jLabel_title1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title1.setText("Citizen / Non-Citizen Login");
        jLabel_title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PReturn.setBackground(new java.awt.Color(255, 0, 0));
        PReturn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        PReturn.setForeground(new java.awt.Color(255, 255, 255));
        PReturn.setText("Return");
        PReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PReturnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Username");

        PUsername.setToolTipText("Chye Zee Ching");
        PUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUsernameActionPerformed(evt);
            }
        });

        PSignIn.setBackground(new java.awt.Color(0, 102, 102));
        PSignIn.setForeground(new java.awt.Color(255, 255, 255));
        PSignIn.setText("Sign In");
        PSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSignInActionPerformed(evt);
            }
        });

        PForgot.setBackground(new java.awt.Color(0, 102, 102));
        PForgot.setForeground(new java.awt.Color(255, 255, 255));
        PForgot.setText("Forgot Username/Password");
        PForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PForgotActionPerformed(evt);
            }
        });

        PPassword.setToolTipText("");
        PPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPasswordActionPerformed(evt);
            }
        });

        PSeenPw.setForeground(new java.awt.Color(102, 102, 102));
        PSeenPw.setText("Seen Password");
        PSeenPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSeenPwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(PSignIn)
                                .addGap(126, 126, 126))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(PForgot)
                                .addGap(70, 70, 70)))
                        .addComponent(PReturn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(PUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PSeenPw)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PSeenPw))
                        .addGap(12, 12, 12)
                        .addComponent(PSignIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PForgot)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PReturn)
                        .addContainerGap())))
        );

        PPassword.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PReturnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Page3_People PeoplePage= new Page3_People();
        PeoplePage.setVisible(true);
    }//GEN-LAST:event_PReturnActionPerformed

    private void PUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUsernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_PUsernameActionPerformed

    private void PSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSignInActionPerformed
        try {
            // TODO signin here:
            File peofile = new File("People.txt");
            Scanner sc = new Scanner(peofile);
            String username = "";
            String password = "";
            
            String txt_username = PUsername.getText();
            String txt_password = String.valueOf(PPassword.getPassword());
            
            boolean isFound = false;
            
            while (sc.hasNextLine() && !isFound) {
                // Data from txt file
                String data = sc.nextLine(); // file content
                if (data.split(":")[0].replaceAll("\\s+", "").equals("Username")) {
                    username = data.split(":")[1].replaceAll("\\s+", "");
                }
                if (data.split(":")[0].replaceAll("\\s+", "").equals("Password")) {
                    password = data.split(":")[1].replaceAll("\\s+", "");
                    if (username.equals(txt_username) && password.equals(txt_password)) {
                        isFound = true;
                        this.dispose();
                        PPage3_PAfterLogin AfterLoginPage= new PPage3_PAfterLogin();
                        AfterLoginPage.setVisible(true);
                    }
                }
                

            }
            
            if (!isFound) {
                JOptionPane.showMessageDialog(PUsername, "Invalid Credentials");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PPage2_Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_PSignInActionPerformed

    private void PForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PForgotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PForgotActionPerformed

    private void PPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPasswordActionPerformed
        // TODO add your handling code here:
        String name = PUsername.getText();
        String pw = PPassword.getText();

    }//GEN-LAST:event_PPasswordActionPerformed

    private void PSeenPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSeenPwActionPerformed
        // Show and hide password:
        if(PSeenPw.isSelected()){
            PPassword.setEchoChar((char)0);
        }else{
            PPassword.setEchoChar((char)'*');
        }
    }//GEN-LAST:event_PSeenPwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPage2_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPage2_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPage2_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPage2_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPage2_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PForgot;
    private javax.swing.JPasswordField PPassword;
    private javax.swing.JButton PReturn;
    private javax.swing.JCheckBox PSeenPw;
    private javax.swing.JButton PSignIn;
    private javax.swing.JTextField PUsername;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_title1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
